// vue/src/App.vue
<template>
    <div id="container">
        <DxAccordion
            :data-source="employees"
            :collapsible="true"
            :multiple="true"
            animation-duration="450"
        >
            <template #title="{ data }">
                {{ data.FirstName + " " + data.LastName }}
            </template>
            <template #item="{ data }">
                {{ data.Position + " from " + data.State }}
            </template>
        </DxAccordion> 
    </div>
</template>

<script>
    import { DxAccordion } from 'devextreme-vue/accordion';
    import { employees } from './data.js';

    export default {
        components: {
            DxAccordion
        },
        data() {
            return {
                employees
            };
        }
    }
</script>

<style>
    #container {
        width: 40%;
    }
</style>

// react/src/App.js
import React from 'react';
import 'devextreme/dist/css/dx.light.css';
import { Accordion } from 'devextreme-react/accordion';
import { employees } from './data.js';

const customTitle = (data) => {
  return data.FirstName + " " + data.LastName;
}
const customItem = (data) => {
  return data.Position + " from " + data.State;
}
function App() {
  return (
    <div id="container">
      <Accordion
        dataSource={employees}
        collapsible={true}
        multiple={true}
        animationDuration="450"
        itemTitleRender={customTitle}
        itemRender={customItem}
      />
    </div>
  );
}

export default App;
